spring:
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:/var/outline/outline-prod.sqlite}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
outline:
  debug:
    enabled: false
  storage:
    upload-dir: ${OUTLINE_UPLOAD_DIR:/var/outline/uploads}
logging:
  level:
    com.outline: INFO
